CREATE TABLE `component` (
  `component_id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `inner_name` varchar(45) NOT NULL DEFAULT '' COMMENT '内部名称',
  `inner_desc` varchar(45) NOT NULL DEFAULT '' COMMENT '内部描述',
  `name` varchar(45) NOT NULL DEFAULT '' COMMENT '三方平台名称',
  `desc` varchar(45) NOT NULL DEFAULT '' COMMENT '三方平台描述',
  `app_id` varchar(100) NOT NULL DEFAULT '' COMMENT '三方平台AppID',
  `app_secret` varchar(32) NOT NULL DEFAULT '' COMMENT '三方平台AppSecret',
  `verify_token` varchar(45) NOT NULL DEFAULT '' COMMENT '三方平台消息验证token',
  `verify_ticket` varchar(95) NOT NULL DEFAULT '' COMMENT '三方平台消息验证verify_ticket',
  `aes_key` varchar(43) NOT NULL DEFAULT '' COMMENT '三方平台消息解密解密Key',
  `validate_filename` varchar(43) NOT NULL DEFAULT '' COMMENT '三方平台验证域名-文件名',
  `validate_content` varchar(43) NOT NULL DEFAULT '' COMMENT '三方平台验证域名-文件内容',
  `field1` varchar(45) NOT NULL DEFAULT '' COMMENT '备用字段',
  `field2` varchar(45) NOT NULL DEFAULT '' COMMENT '备用字段2',
  `is_deleted` tinyint(1) NOT NULl DEFAULT 0 COMMENT '软删除标记',
  `create_user` varchar(45) NOT NULL DEFAULT 0 comment '新建记录的用户',
  `update_user` varchar(45) NOT NULL DEFAULT 0 comment '最后一次操作的用户',
  `created_at` timestamp NOT NULL DEFAULT '1970-01-01 08:00:01' COMMENT '记录添加时间',
  `updated_at` timestamp NOT NULL DEFAULT '1970-01-01 08:00:01' COMMENT '记录更新时间',
  PRIMARY KEY (`component_id`),
  UNIQUE KEY `uniq_app_id` (`app_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8 COMMENT = '三方平台表';
CREATE TABLE `component_ext` (
  `component_ext_id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `component_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '关联的三方平台ID',
  `field1` varchar(45) NOT NULL DEFAULT '' COMMENT '备用字段',
  `field2` varchar(45) NOT NULL DEFAULT '' COMMENT '备用字段2',
  `created_at` timestamp NOT NULL DEFAULT '1970-01-01 08:00:01' COMMENT '记录添加时间',
  `updated_at` timestamp NOT NULL DEFAULT '1970-01-01 08:00:01' COMMENT '记录更新时间',
  `config` TEXT COMMENT '配置文件',
  `is_deleted` tinyint(1) NOT NULl DEFAULT 0 COMMENT '软删除标记',
  `create_user` varchar(45) NOT NULL DEFAULT 0 comment '新建记录的用户',
  `update_user` varchar(45) NOT NULL DEFAULT 0 comment '最后一次操作的用户',
  PRIMARY KEY (`component_ext_id`),
  KEY `idx_component_app_id` (`component_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8 COMMENT = '三方平台extra配置信息';
CREATE TABLE `mini_program` (
  `mini_program_id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `component_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '关联的三方平台ID',
  `company_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '公司id',
  `inner_name` varchar(45) NOT NULL DEFAULT '' COMMENT '内部名称',
  `inner_desc` varchar(45) NOT NULL DEFAULT '' COMMENT '内部描述',
  `nick_name` varchar(45) NOT NULL DEFAULT '' COMMENT '授权方昵称',
  `head_img` varchar(255) NOT NULL DEFAULT '' COMMENT '小程序头像',
  `app_id` varchar(100) NOT NULL DEFAULT '' COMMENT '小程序AppID',
  `user_name` varchar(45) NOT NULL DEFAULT '' COMMENT '原始ID,审核推送要用',
  `principal_name` varchar(45) NOT NULL DEFAULT '' COMMENT '小程序主体名称',
  `qrcode_url` varchar(255) NOT NULL DEFAULT '' COMMENT '二维码图片的URL',
  `desc` varchar(255) NOT NULL DEFAULT '' COMMENT '小程序平台描述',
  `authorizer_refresh_token` varchar(100) NOT NULL DEFAULT '' COMMENT '获取（刷新）授权公众号或小程序的接口调用凭据',
  `user_version` varchar(43) NOT NULL DEFAULT '' COMMENT '当前版本',
  `field1` varchar(45) NOT NULL DEFAULT '' COMMENT '备用字段',
  `field2` varchar(45) NOT NULL DEFAULT '' COMMENT '备用字段2',
  `is_deleted` tinyint(1) NOT NULl DEFAULT 0 COMMENT '软删除标记',
  `create_user` varchar(45) NOT NULL DEFAULT 0 comment '新建记录的用户',
  `update_user` varchar(45) NOT NULL DEFAULT 0 comment '最后一次操作的用户',
  `created_at` timestamp NOT NULL DEFAULT '1970-01-01 08:00:01' COMMENT '记录添加时间',
  `updated_at` timestamp NOT NULL DEFAULT '1970-01-01 08:00:01' COMMENT '记录更新时间',
  PRIMARY KEY (`mini_program_id`),
  KEY `idx_app_id` (`app_id`),
  KEY `idx_user_name` (`user_name`),
  KEY `idx_authorizer_refresh_token` (`authorizer_refresh_token`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8 COMMENT = '已授权小程序表';
CREATE TABLE `mini_program_ext` (
  `mini_program_ext_id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `component_app_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '关联的三方平台ID',
  `mini_program_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '小程序id',
  `company_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '公司ID',
  `template_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '模板id',
  `config` text COMMENT '自定义配置',
  `field1` varchar(45) NOT NULL DEFAULT '' COMMENT '备用字段',
  `field2` varchar(45) NOT NULL DEFAULT '' COMMENT '备用字段2',
  `is_deleted` tinyint(1) NOT NULl DEFAULT 0 COMMENT '软删除标记',
  `create_user` varchar(45) NOT NULL DEFAULT 0 comment '新建记录的用户',
  `update_user` varchar(45) NOT NULL DEFAULT 0 comment '最后一次操作的用户',
  `created_at` timestamp NOT NULL DEFAULT '1970-01-01 08:00:01' COMMENT '记录添加时间',
  `updated_at` timestamp NOT NULL DEFAULT '1970-01-01 08:00:01' COMMENT '记录更新时间',
  PRIMARY KEY (`mini_program_ext_id`),
  KEY `idx_template_id` (`template_id`),
  KEY `idx_company_id` (`company_id`),
  KEY `idx_mini_program_id` (`mini_program_id`),
  KEY `idx_component_app_id` (`component_app_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8 COMMENT = '小程序extra配置信息';
CREATE TABLE `mini_program_template` (
  `mini_program_template_id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `component_app_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '关联的三方平台ID',
  `template_id` int(11) NOT NULL DEFAULT '0' COMMENT '模板id',
  `draft_id` int(11) NOT NULL DEFAULT '0' COMMENT '草稿id',
  `wechat_version` varchar(20) NOT NULL DEFAULT '' COMMENT '微信基础库版本',
  `user_version` varchar(45) NOT NULL DEFAULT '' COMMENT '模版版本号，开发者自定义字段',
  `user_desc` varchar(45) NOT NULL DEFAULT '' COMMENT '模版描述开发者自定义字段',
  `create_time` varchar(15) NOT NULL DEFAULT '' COMMENT '开发者上传草稿时间',
  `desc` varchar(45) NOT NULL DEFAULT '' COMMENT '描述,备注',
  `field1` varchar(45) NOT NULL DEFAULT '' COMMENT '备用字段',
  `field2` varchar(45) NOT NULL DEFAULT '' COMMENT '备用字段2',
  `is_deleted` tinyint(1) NOT NULl DEFAULT 0 COMMENT '软删除标记',
  `create_user` varchar(45) NOT NULL DEFAULT 0 comment '新建记录的用户',
  `update_user` varchar(45) NOT NULL DEFAULT 0 comment '最后一次操作的用户',
  `created_at` timestamp NOT NULL DEFAULT '1970-01-01 08:00:01' COMMENT '记录添加时间',
  `updated_at` timestamp NOT NULL DEFAULT '1970-01-01 08:00:01' COMMENT '记录更新时间',
  PRIMARY KEY (`mini_program_template_id`),
  UNIQUE KEY `uniq_component_app_template_id` (`template_id`, `component_app_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8 COMMENT = '小程序模板表';
CREATE TABLE `mini_program_template_draft` (
  `mini_program_template_draft_id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `component_app_id` int(11) NOT NULL DEFAULT '0' COMMENT '关联的三方平台ID',
  `draft_id` varchar(255) NOT NULL DEFAULT '' COMMENT '草稿id',
  `user_version` varchar(45) NOT NULL DEFAULT '' COMMENT '模版版本号，开发者自定义字段',
  `user_desc` varchar(45) NOT NULL DEFAULT '' COMMENT '模版描述开发者自定义字段',
  `create_time` varchar(45) NOT NULL DEFAULT '' COMMENT '开发者上传草稿时间',
  `desc` varchar(45) NOT NULL DEFAULT '' COMMENT '描述,备注',
  `field1` varchar(45) NOT NULL DEFAULT '' COMMENT '备用字段',
  `field2` varchar(45) NOT NULL DEFAULT '' COMMENT '备用字段2',
  `is_deleted` tinyint(1) NOT NULl DEFAULT 0 COMMENT '软删除标记',
  `create_user` varchar(45) NOT NULL DEFAULT 0 comment '新建记录的用户',
  `update_user` varchar(45) NOT NULL DEFAULT 0 comment '最后一次操作的用户',
  `created_at` timestamp NOT NULL DEFAULT '1970-01-01 08:00:01' COMMENT '记录添加时间',
  `updated_at` timestamp NOT NULL DEFAULT '1970-01-01 08:00:01' COMMENT '记录更新时间',
  PRIMARY KEY (`mini_program_template_draft_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8 COMMENT = '小程序模板草稿表';
CREATE TABLE `release` (
  `release_id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `component_app_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '关联的三方平台ID',
  `mini_program_id` int(11) NOT NULL DEFAULT '0' COMMENT '小程序id',
  `template_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '模板id',
  `user_version` varchar(45) NOT NULL DEFAULT '' COMMENT '代码版本号',
  `user_desc` varchar(45) NOT NULL DEFAULT '' COMMENT '代码描述',
  `ext_json` varchar(45) NOT NULL DEFAULT '' COMMENT '自定义配置',
  `desc` varchar(45) NOT NULL DEFAULT '' COMMENT '描述,备注',
  `status` varchar(45) NOT NULL DEFAULT '' COMMENT '10已上传.11已提交审核.13审核未通过.20发布成功',
  `audit_id` varchar(45) NOT NULL DEFAULT '' COMMENT '最新的微信审核id',
  `field1` varchar(45) NOT NULL DEFAULT '' COMMENT '备用字段',
  `field2` varchar(45) NOT NULL DEFAULT '' COMMENT '备用字段2',
  `is_deleted` tinyint(1) NOT NULl DEFAULT 0 COMMENT '软删除标记',
  `create_user` varchar(45) NOT NULL DEFAULT 0 comment '新建记录的用户',
  `update_user` varchar(45) NOT NULL DEFAULT 0 comment '最后一次操作的用户',
  `created_at` timestamp NOT NULL DEFAULT '1970-01-01 08:00:01' COMMENT '记录添加时间',
  `updated_at` timestamp NOT NULL DEFAULT '1970-01-01 08:00:01' COMMENT '记录更新时间',
  PRIMARY KEY (`release_id`),
  KEY `idx_template_id` (`template_id`),
  KEY `idx_mini_program_id` (`mini_program_id`),
  KEY `idx_component_app_id` (`component_app_id`),
  KEY `idx_status` (`status`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8 COMMENT = '发版申请记录表';
CREATE TABLE `release_audit` (
  `release_audit_id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `component_app_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '关联的三方平台ID',
  `mini_program_id` int(11) NOT NULL DEFAULT '0' COMMENT '小程序id',
  `release_id` varchar(45) NOT NULL DEFAULT '' COMMENT '发版自增id',
  `status` varchar(45) NOT NULL DEFAULT '' COMMENT '状态.1成功',
  `reason` varchar(45) NOT NULL DEFAULT '' COMMENT '失败原因',
  `field1` varchar(45) NOT NULL DEFAULT '' COMMENT '备用字段',
  `field2` varchar(45) NOT NULL DEFAULT '' COMMENT '备用字段2',
  `is_deleted` tinyint(1) NOT NULl DEFAULT 0 COMMENT '软删除标记',
  `create_user` varchar(45) NOT NULL DEFAULT 0 comment '新建记录的用户',
  `update_user` varchar(45) NOT NULL DEFAULT 0 comment '最后一次操作的用户',
  `created_at` timestamp NOT NULL DEFAULT '1970-01-01 08:00:01' COMMENT '记录添加时间',
  `updated_at` timestamp NOT NULL DEFAULT '1970-01-01 08:00:01' COMMENT '记录更新时间',
  PRIMARY KEY (`release_audit_id`),
  KEY `idx_release_id` (`release_id`),
  KEY `idx_mini_program_id` (`mini_program_id`),
  KEY `idx_component_app_id` (`component_app_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8 COMMENT = '发版审核申请结果表';
CREATE TABLE `template_ext` (
  `template_ext_id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `component_app_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '关联的三方平台ID',
  `template_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '模板id',
  `config` text COMMENT '自定义配置',
  `field1` varchar(45) NOT NULL DEFAULT '' COMMENT '备用字段',
  `field2` varchar(45) NOT NULL DEFAULT '' COMMENT '备用字段2',
  `is_deleted` tinyint(1) NOT NULl DEFAULT 0 COMMENT '软删除标记',
  `create_user` varchar(45) NOT NULL DEFAULT 0 comment '新建记录的用户',
  `update_user` varchar(45) NOT NULL DEFAULT 0 comment '最后一次操作的用户',
  `created_at` timestamp NOT NULL DEFAULT '1970-01-01 08:00:01' COMMENT '记录添加时间',
  `updated_at` timestamp NOT NULL DEFAULT '1970-01-01 08:00:01' COMMENT '记录更新时间',
  PRIMARY KEY (`template_ext_id`),
  KEY `idx_template_id` (`template_id`),
  KEY `idx_component_app_id` (`component_app_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8 COMMENT = '模板公共配置信息';