CREATE TABLE `component_template` (
  `component_template_id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `component_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '关联的三方平台ID',
  `template_id` int(11) NOT NULL DEFAULT '0' COMMENT '三方平台模板id',
  `user_version` varchar(45) NOT NULL DEFAULT '' COMMENT '模版版本号，开发者自定义字段',
  `user_desc` varchar(45) NOT NULL DEFAULT '' COMMENT '模版描述开发者自定义字段',
  `create_time` timestamp NOT NULL DEFAULT '1970-01-01 08:00:01' COMMENT '开发者上传草稿时间',
  `branch` varchar(45) NOT NULL DEFAULT '' COMMENT '分支',
  `source_miniprogram` varchar(45) NOT NULL DEFAULT '' COMMENT '来源小程序名称',
  `source_miniprogram_appid` varchar(45) NOT NULL DEFAULT '' COMMENT '来源小程序appid',
  `developer` varchar(45) NOT NULL DEFAULT '' COMMENT '开发者',
  `field1` varchar(45) NOT NULL DEFAULT '' COMMENT '备用字段',
  `field2` varchar(45) NOT NULL DEFAULT '' COMMENT '备用字段2',
  `is_deleted` tinyint(1) NOT NULl DEFAULT 0 COMMENT '软删除标记',
  `create_user` varchar(45) NOT NULL DEFAULT 0 comment '新建记录的用户',
  `update_user` varchar(45) NOT NULL DEFAULT 0 comment '最后一次操作的用户',
  `created_at` timestamp NOT NULL DEFAULT '1970-01-01 08:00:01' COMMENT '记录添加时间',
  `updated_at` timestamp NOT NULL DEFAULT '1970-01-01 08:00:01' COMMENT '记录更新时间',
  PRIMARY KEY (`component_template_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8 COMMENT = '平台模板表';